# Generated by Django 2.2.2 on 2019-07-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
